# Generated by Django 5.0.6 on 2025-05-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_provisioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresultmodel',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
