# Generated by Django 5.0.6 on 2025-05-23 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskresultmodel",
            name="task_id",
        ),
        migrations.AddField(
            model_name="taskresultmodel",
            name="date_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskresultmodel",
            name="id",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="DashboardModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("uid", models.CharField(blank=True, max_length=128, null=True)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("org_id", models.CharField(blank=True, max_length=64, null=True)),
                ("folder_uid", models.CharField(blank=True, max_length=128, null=True)),
                ("url", models.URLField(blank=True, max_length=512, null=True)),
                ("config_json", models.JSONField(blank=True, null=True)),
                ("panels", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("data_sources", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "visualization_dashboard",
            },
        ),
        migrations.CreateModel(
            name="ServiceAccountModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("account_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=128)),
                ("is_disabled", models.BooleanField(default=False)),
                ("role", models.CharField(max_length=32)),
                ("token", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "visualization_service_account",
            },
        ),
        migrations.CreateModel(
            name="UserFolderModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("uid", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("org_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "created_by_task",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "visualization_folder",
            },
        ),
        migrations.CreateModel(
            name="FolderPermissionModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("folder_uid", models.CharField(max_length=128)),
                (
                    "permission",
                    models.IntegerField(
                        choices=[(1, "View"), (2, "Edit"), (4, "Admin")]
                    ),
                ),
                (
                    "service_account",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="monitoring.serviceaccountmodel",
                        to_field="account_id",
                    ),
                ),
            ],
            options={
                "db_table": "visualization_folder_permission",
                "unique_together": {("service_account", "folder_uid")},
            },
        ),
    ]
