# Generated by Django 5.0.6 on 2025-05-23 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_remove_taskresultmodel_task_id_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringProjectModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "project_type",
                    models.CharField(
                        choices=[("LOG", "LOG"), ("METRIC", "METRIC")], max_length=32
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "INITIATED"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("READY", "READY"),
                            ("FAILED", "FAILED"),
                        ],
                        default="INITIATED",
                        max_length=32,
                    ),
                ),
                ("agent_context", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.OneToOneField(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project",
                        to="monitoring.dashboardmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.user",
                    ),
                ),
                (
                    "user_folder",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="monitoring.userfoldermodel",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_project",
            },
        ),
    ]
