# Generated by Django 5.0.6 on 2025-05-23 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_monitoringprojectmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardmodel",
            name="project",
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_model",
                to="monitoring.monitoringprojectmodel",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringprojectmodel",
            name="dashboard",
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoring_project",
                to="monitoring.dashboardmodel",
            ),
        ),
    ]
