# Generated by Django 5.0.6 on 2025-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_dashboardmodel_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceaccountmodel",
            name="account_id",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
