# Generated by Django 5.0.6 on 2025-05-23 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_alter_serviceaccountmodel_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringprojectmodel",
            name="service_account",
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoring_project",
                to="monitoring.serviceaccountmodel",
            ),
        ),
        migrations.AddField(
            model_name="serviceaccountmodel",
            name="project",
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_account_model",
                to="monitoring.monitoringprojectmodel",
            ),
        ),
    ]
