# Generated by Django 5.0.6 on 2025-05-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0006_monitoringprojectmodel_service_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicDashboardModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("uid", models.CharField(blank=True, max_length=128, null=True)),
                ("public_url", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "dashboard",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_dashboard_model",
                        to="monitoring.dashboardmodel",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_dashboard_model",
                        to="monitoring.monitoringprojectmodel",
                    ),
                ),
            ],
            options={
                "db_table": "visualization_public_dashboard",
            },
        ),
        migrations.AddField(
            model_name="monitoringprojectmodel",
            name="public_dashboard",
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoring_project",
                to="monitoring.publicdashboardmodel",
            ),
        ),
    ]
